---
# tasks file for fluentd-helper
- name: create secure-forward folder for cert
  file:
    path: "/home/{{ owner }}/secure-forward/"
    state: directory
    mode: 0755
    owner: "{{ owner }}"
    group: "{{ owner }}"
- name: put cert files onto remote server
  copy:
    src: "secure-forward/ca-cert.pem"
    dest: "/home/{{ owner }}/secure-forward/ca-cert.pem"
    force: yes
    mode: 0644
    owner: "{{ owner }}"
    group: "{{ owner }}"
- name: install gelf plugin
  command: "sudo /usr/sbin/td-agent-gem install gelf"
- name: install out_gelf plugin
  command: "sudo wget https://raw.githubusercontent.com/emsearcy/fluent-plugin-gelf/master/lib/fluent/plugin/out_gelf.rb"
  args:
    chdir: "/etc/td-agent/plugin"
- name: td-agent.conf
  template: src=fluentd.conf.j2 dest=/etc/td-agent/td-agent.conf owner={{ fluentd.user }}
  notify:
    - restart td-agent
